export const data =
    [{ "company_name": "Yakidoo", "location": "Buenavista", "industry_type": "Medical Specialities" },
    { "company_name": "Brainbox", "location": "Houmt Souk", "industry_type": "n/a" },
    { "company_name": "Roodel", "location": "Tambulig", "industry_type": "Oil Refining/Marketing" },
    { "company_name": "Photobug", "location": "Goz Beïda", "industry_type": "Major Chemicals" },
    { "company_name": "Oba", "location": "Liwu", "industry_type": "Oil & Gas Production" },
    { "company_name": "Buzzbean", "location": "Pulosari", "industry_type": "Natural Gas Distribution" },
    { "company_name": "Browseblab", "location": "Sampacho", "industry_type": "Biotechnology: In Vitro & In Vivo Diagnostic Substances" },
    { "company_name": "Bluezoom", "location": "Wonokerso", "industry_type": "Major Pharmaceuticals" },
    { "company_name": "Twitterworks", "location": "Pingshan", "industry_type": "Business Services" },
    { "company_name": "Blogpad", "location": "Leigu", "industry_type": "Mining & Quarrying of Nonmetallic Minerals (No Fuels)" },
    { "company_name": "Wikido", "location": "Safonovo", "industry_type": "EDP Services" },
    { "company_name": "Oloo", "location": "Penedo", "industry_type": "n/a" },
    { "company_name": "Meemm", "location": "Myingyan", "industry_type": "Industrial Machinery/Components" },
    { "company_name": "Skidoo", "location": "Jeziorany", "industry_type": "Professional Services" },
    { "company_name": "Browsebug", "location": "Sintung Timur", "industry_type": "Specialty Insurers" },
    { "company_name": "Twinder", "location": "Carpenter", "industry_type": "n/a" },
    { "company_name": "Kwimbee", "location": "Xinba", "industry_type": "Finance: Consumer Services" },
    { "company_name": "Voonix", "location": "Tuojiang", "industry_type": "Major Banks" },
    { "company_name": "Centimia", "location": "Chonchi", "industry_type": "Coal Mining" },
    { "company_name": "Roombo", "location": "L'Île-Perrot", "industry_type": "Restaurants" },
    { "company_name": "Twitternation", "location": "Jiuxian", "industry_type": "Major Pharmaceuticals" },
    { "company_name": "Zoonder", "location": "Nouaseur", "industry_type": "n/a" },
    { "company_name": "Quinu", "location": "Haodi", "industry_type": "Recreational Products/Toys" },
    { "company_name": "Midel", "location": "Maythalūn", "industry_type": "Savings Institutions" },
    { "company_name": "Chatterbridge", "location": "Rechitsy", "industry_type": "Real Estate Investment Trusts" },
    { "company_name": "Divanoodle", "location": "Pangradin Satu", "industry_type": "Major Pharmaceuticals" },
    { "company_name": "Tagopia", "location": "Baoquanshan", "industry_type": "n/a" },
    { "company_name": "Oba", "location": "Serhetabat", "industry_type": "n/a" },
    { "company_name": "Dabtype", "location": "Lorena", "industry_type": "Clothing/Shoe/Accessory Stores" },
    { "company_name": "Jabberstorm", "location": "Budaka", "industry_type": "Major Banks" },
    { "company_name": "Fanoodle", "location": "Kiraman", "industry_type": "Banks" },
    { "company_name": "Mydeo", "location": "Dalang", "industry_type": "Aerospace" },
    { "company_name": "Divape", "location": "La Huerta", "industry_type": "n/a" },
    { "company_name": "Realblab", "location": "Yanqian", "industry_type": "Forest Products" },
    { "company_name": "Meembee", "location": "Muskegon", "industry_type": "Electric Utilities: Central" },
    { "company_name": "Kare", "location": "Haibeitou", "industry_type": "Major Banks" },
    { "company_name": "Jaxbean", "location": "Mwembe", "industry_type": "n/a" },
    { "company_name": "Camido", "location": "Liuji", "industry_type": "Major Chemicals" },
    { "company_name": "Centizu", "location": "Huakoulongtan", "industry_type": "Department/Specialty Retail Stores" },
    { "company_name": "Jetpulse", "location": "Sanfang", "industry_type": "Mining & Quarrying of Nonmetallic Minerals (No Fuels)" },
    { "company_name": "Rhybox", "location": "Santana do Paraíso", "industry_type": "Investment Bankers/Brokers/Service" },
    { "company_name": "Geba", "location": "Xinxing", "industry_type": "Computer Software: Prepackaged Software" },
    { "company_name": "Jayo", "location": "Phetchaburi", "industry_type": "n/a" },
    { "company_name": "Voonyx", "location": "Moyale", "industry_type": "Real Estate Investment Trusts" },
    { "company_name": "Kwilith", "location": "Talashkino", "industry_type": "Computer Software: Prepackaged Software" },
    { "company_name": "Katz", "location": "Dangchang Chengguanzhen", "industry_type": "n/a" },
    { "company_name": "Dynazzy", "location": "Arvika", "industry_type": "Investment Bankers/Brokers/Service" },
    { "company_name": "Myworks", "location": "Umuahia", "industry_type": "Oil & Gas Production" },
    { "company_name": "Riffwire", "location": "Camingawan", "industry_type": "EDP Services" },
    { "company_name": "Thoughtblab", "location": "Shakīso", "industry_type": "Major Banks" }]